export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SHOW_SUBJECT = 'SHOW_SUBJECT';
export const HIDE_SUBJECT = 'HIDE_SUBJECT';
