export const LOAD_MY_TIMETABLE = 'LOAD_MY_TIMETABLE';
export const LOAD_MY_TIMETABLE_DONE = 'LOAD_MY_TIMETABLE_DONE';
export const LOAD_MY_TIMETABLE_FAIL = 'LOAD_MY_TIMETABLE_FAIL';

export const LOAD_COURSE_TIMETABLE = 'LOAD_COURSE_TIMETABLE';
export const LOAD_COURSE_TIMETABLE_DONE = 'LOAD_COURSE_TIMETABLE_DONE';
export const LOAD_COURSE_TIMETABLE_FAIL = 'LOAD_COURSE_TIMETABLE_FAIL';
export const SHOW_EXCHANGE_MODE_TIMETABLE = 'SHOW_EXCHANGE_MODE_TIMETABLE';

export const SHOW_COURSE_TIMETABLE = 'SHOW_COURSE_TIMETABLE';
export const HIDE_COURSE_TIMETABLE = 'HIDE_COURSE_TIMETABLE';
export const CONFIRM_EXCHANGE_REQUEST = 'CONFIRM_EXCHANGE_REQUEST';
export const CANCEL_EXCHANGE_MODE = 'CANCEL_EXCHANGE_MODE';

export const SHOW_DETAIL = 'SHOW_DETAIL';
export const HIDE_DETAIL = 'HIDE_DETAIL';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const RENEW = 'RENEW';
