services:
  - docker

env:  
  global:
    - NODEJS_DONE=false
    - CSHARP_DONE=false

matrix:
  include:
    - language: node_js
      node_js:
        - node
      cache:
        directories:
          - WebApp/node_modules
      before_install:
        - cd WebApp/
      install:
       - npm install
      script:
        - npm run lint
        - npm run test:CI
      after_script:
        - export NODEJS_DONE=true        
    - language: csharp
      mono: none
      dotnet: 2.1.4
      install:
        - dotnet restore
      script:
        - find Tests/ -type f -name "*.csproj" -exec dotnet test {} \;
      after_script:
        - export CSHARP_DONE=true

before_deploy:        
  - cd $TRAVIS_BUILD_DIR

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $REGION
  app: $APP_NAME
  env: $DEPLOY_ENV
  bucket_name: $DEPLOY_BUCKET_NAME
  on:
    all_branches: true
    condition: $NODEJS_DONE && $CSHARP_DONE
#    branch: master        
        
notifications:
  email: false
  slack:
    secure: sIlVzWcYHOXf20aeoTCBAV2j7PhUtQu24K3lWtm7K60pEpV8lEyEZTWgEyHk9LihFdyBwQJJvkrsSdSNRtMEPlRwa/AnXghk0yql6I6AwRxpJdG8k4lDPJIvM9enIUAzpPy0NaiqSKW9tufxpBRizTqTNeYCX2dGWg5y/IfRKh944cOG+d8GHD3wS1Cgw4mnE38EKNu2RDJK/0MKolxhUZ9llMBKziw/AUhXBJEw/ID7thjvUnXRvOP2JZhoXbPm9ae0r6rDRZ+9qSnnFFjHnjTWj6STbP5MN0WF2KuyeBDAX7K6NdTT+NUGnihgFp9Yyi3Pkcp5oEZb/iv2ujk4FSwEaNZvTh8opeUi/V4oohgUVIev6xJApANpM2/pTGFu10qeWbEdBeJ/EYRZgtGGz2Fst9CugY3y5FDtkr9MS6Br3LfYuPwQ1XiGo/+5r6I6CXXgkoKoYlaCeFEkV3m/zJNipWQYIWXRO7E7BMTIQvMUuR9AZpBetORwOUkeMk28R9dDtDt3fP6tocE9uwGgZjL8vGUT+AG/I/wXcJVSOg6EXomQ9VBSy5Fkhn6W8fiLliO6S1Pkuo9OAZfcwlxoqhrPDoip0L/l7nJWksbSl3JSoyXBc6qa8andIO+/K54Cf2M29CyanQxeUHmZuweO9QOR+2QSWn3RUoz1O/AcbIo=
  on_success: always
  on_failure: always