version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    volumes:
      - ./logs:/app/logs
    ports:
      - '80:80'
  ci:
    build:
      context: .
      dockerfile: Dockerfile-CI
    image: tests
