version: '3.4'
services:
 swapify-stg:
  build:
   context: .
   dockerfile: Dockerfile
  image: swapify-app-stage
  container_name: swapify-stg
  volumes:   
   - ./logs_stg:/app/logs
   - ./../Swapify/FixedDB/Course.json:/app/Course.json
  restart: unless-stopped
  expose:
   - 5020   
  environment:
   - ASPNETCORE_ENVIRONMENT=Production
   - ASPNETCORE_URLS=http://+:5020
   - BaseUrl=https://swapify.fri.uniza.sk
   - JwtSecret=##JWTKEY##
   - NODE_ENV=production  
  depends_on:
   - mongodb-stg
  links:
   - mongodb-stg
 mongodb-stg:
  image: mongo
  container_name: mongodb-stg
  volumes:
   - ./data_stg:/data/db
 nginx-stg:
  restart: unless-stopped
  image: nginx
  container_name: nginx-stg
  volumes:
   - ./nginx_stg.conf:/etc/nginx/conf.d/default.conf
   - ./../Swapify/certbot/conf:/etc/letsencrypt
   - ./../Swapify/certbot/www:/var/www/certbot
  ports:
   - 81:80
   - 444:443
  command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
 certbot-stg:
  image: certbot/certbot
  volumes:
   - ./../Swapify/certbot/conf:/etc/letsencrypt
   - ./../Swapify/certbot/www:/var/www/certbot
  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"