version: '3.4'

services:
  webapi:
    image: webapi
    container_name: swapify
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    restart: unless-stopped
    depends_on:
      - mongodb
      - react-app
    links:
      - mongodb
      - react-app
    volumes:
      - app-volume:/app/wwwroot
      - ./logs:/app/logs   
      - ./Tests/FixedDB:/Tests/FixedDB
    expose:
      - 5020
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27018:27017
    volumes:
      - ./dockerData:/data/db
  reactApp:
    image: react
    container_name: react-app
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    volumes:
      - app-volume:/app/WebApp/dist
  nginx:
    restart: unless-stopped
    image: nginx
    container_name: nginx
    volumes:
      - ./nginxlocal.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
volumes:
     app-volume: 
