version: '3.4'
services:
 swapify:
  build:
   context: .
   dockerfile: Dockerfile
  image: swapify-app-stage
  container_name: swapify-stage
  volumes:   
   - ./logs_stg:/app/logs
   - ./FixedDB/courses_2020_1_29.json:/app/courses_2020_1_29.json
  restart: unless-stopped
  expose:
   - 5020   
  environment:
   - ASPNETCORE_ENVIRONMENT=Production
   - ASPNETCORE_URLS=http://+:5020
   - BaseUrl=https://swapify.fri.uniza.sk
   - JwtSecret=##JWTKEY##
   - NODE_ENV=production  
  depends_on:
   - mongodb
  links:
   - mongodb
 mongodb:
  image: mongo
  container_name: mongodb-stg
  volumes:
   - ./data_stg:/data/db
 nginx:
  restart: unless-stopped
  image: nginx
  container_name: nginx-stg
  volumes:
   - ./nginx.conf:/etc/nginx/conf.d/default.conf
   - ./certbot/conf:/etc/letsencrypt
   - ./certbot/www:/var/www/certbot
  ports:
   - 81:80
   - 444:443
  command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
 certbot:
  image: certbot/certbot
  volumes:
   - ./certbot/conf:/etc/letsencrypt
   - ./certbot/www:/var/www/certbot
  entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"