version: '3'
services:
 swapify:
  build:
   context: .
   dockerfile: Dockerfile
  image: swapify-app
  container_name: swapify
  volumes:   
   - ./logs:/app/logs   
   - ./Tests/FixedDB:/Tests/FixedDB
  restart: unless-stopped
  environment:
   - ASPNETCORE_ENVIRONMENT=Development
   - ASPNETCORE_URLS=http://+:5020
   - BaseUrl=http://localhost
   - JwtSecret=MIIEoQIBAAKCAQEAt3SrODC15RzuJPT5bLPvMLvMeVFcBZQBBpDj9TxvIvp3rI00wehFhvQyGo7rMINxnwO/OLiH50KLZw4+EymHhJ+E1W0ds1Y39lAI+PclXH78NZgeyeCakXlzb+lmi1a4EUUjdowFYb0nNzakJ5NAwbKQOzQyt72Yvh9ojLCVZs4y6MtcE3Ph+hB8pIPKs3cmmxN5TpEbgVLGwy2gGXa7bLDPU6YCkli1BpMWJhWRGZKVrg6btHzDREZRTyDIVTkSCgGDggvpVdWYQiO6bPHE8c7CRogZYN4tlz+qB3u2+A0cFF2JFK0h+9WCiIe16j9RB16GkrONBLNTkpuWUAmyLwIDAQABAoIBACYdZzVVaXUgfZnQC8I54AgP/Ht4G9ZM2amzkKjy1WQ/BX4kGEHxMADJ218JMnPx2zleXew66oFxoeTXYK46gp1bRw3QjcskrpvOJQ8Uyf5do6i+4iavM23l/cXSiCuK6NMtuiB3FucnlW4zPAe84EdeAflK7v6dtY5KmD4iseeZtR28otyyCD7SBKnJ914hcDT4qUfY+0MFNuMOSMqPP/UTqPivjMzNaFNVwid90KPwY0EX/m8WWj3tCtHqA9LFYFZV0cDbIUL8Vud8gpkHbv8xyQ0Ka1YbsMdgOj5mOn5+qzRbsTscZyHnfb82DGCJBAIdd145uBJeqiZgOFCBrAECgYEA7xfK50d+PPa73UScolcLXWTDGfJZGmSLsnlphtv/t3ac8wd1vpSO75gz8Y1RwrXJAIUGJ/En4mbhRE9XdWWQWk3wsSl2cY3siSAto6BVJctH+kyb5lfA/HXBdEL/TmFlOjb64Uhy7Z5JNgJa5dchNAHd1kzh/37uhg1DgTBT2g8CgYEAxG2yiCy7fjDc1GXx9yy5uvP3XKSsqj/3Bkt5RZh2hFTEx+kOxWnkcrDjs9cJJLFhXODsyRBAjEDUfdPGgjnKDPKzHSAWeyAYtDZaX8uFTrTNBMO1l80eRAZmaiLvdNVa/XvKCIjjOYLgPCdYNtUL+oS5EJ3wa01jZth6GZ9fReECf2IQYCh8KkrW6DbY7WWoTgEAUwVRYTpyAtow8hdeJIQbIkSLyr9gL0AWLTflvqMd7FNKPDwlrTYu/DYIVNbR0WM4lIAVgX8RtvKHQDDckg/uUJdY1JilZYImyjHlSNHdIKe/5SaBkKHlSiHc1Wtv0S6DlXlQD2G7rhlNV2Klb78CgYEAwExgLn4UY5q0Zd8TvZZ0kXjLnk+8lcOfMvNqWt7CkBRovQkFI/Dh7AIOOP54fgqFNachSEl315aUMEbGHLE0g+6JuSazu4AVjz9yxDt7Wy0XVOW//keZrKDTXG6tHCTPOj8Y77gLMz9UBK/D5ZI2ct/CSWlFd9bATGv7ROBIJiECgYAgTCdNr6BcLnvACX2ETEXn+fDEhwuPtPHeRI3roKGkzpUyiM9wrjk+7cFRYK/vWk7VanJsAZv+uf6mdoy81PN0ugptLiIWKp3GxoSR2zV+thHWSvEA6oBf9rLxRuGn/wwZM5r2tBnoU0JsGYMaD0lT8oxQEgnAu0fGx9/zjG7asw==
   - NODE_ENV=Development
  depends_on:
   - mongodb
  links:
   - mongodb
  expose:
   - 5020
 mongodb:
  image: mongo
  container_name: mongodb
  ports:
   - 27017:27017
#  volumes:
#   - ./data:/data/db
 nginx:
  restart: unless-stopped
  image: nginx
  container_name: nginx
  volumes:
   - ./nginxlocal.conf:/etc/nginx/conf.d/default.conf
  ports:
   - 80:80
