events { }

http {

  map $http_upgrade $connection_upgrade {
      default upgrade;
      ''      close;
    }

    for worker_processes  
  
    # upstream dotnetcore {  
    #     server swapify: 3000;  
    # }

  # server {
  #   listen 80;
  #   server_name http://18.193.17.141/;
  #   return 301 http://18.193.17.141/$request_uri;
  # }

  server {
    # listen 443 ssl;
    # server_name https://18.193.17.141/;
    server_name swapify.fri.uniza.sk;
    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/swapify.fri.uniza.sk/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/swapify.fri.uniza.sk/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # location / {
    #    try_files $uri $uri/ /index.html?$args;
    #    proxy_pass http://:::80/;
    #    proxy_set_header X-Real-IP  $remote_addr;
    #    proxy_set_header X-Forwarded-For $remote_addr;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Forwarded-Proto $scheme;
    #    proxy_redirect http://:::80/ $scheme://$http_host/;
    #    proxy_http_version 1.1;
    #    proxy_set_header Upgrade $http_upgrade;
    #    proxy_set_header Connection $connection_upgrade;
    #    proxy_read_timeout 20d;
    #    proxy_buffering off;
    # }
  }

   server {
    if ($host = swapify.fri.uniza.sk) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80 ;
    listen [::]:80 ;
      server_name swapify.fri.uniza.sk;
      return https://swapify.fri.uniza.sk; # managed by Certbot
      # return 404; # managed by Certbot
  }
}
