name: Actions with docker
on:
  push:

jobs:  
  action_build:
    name: actions_build
    runs-on: ubuntu-latest
    
    steps:
    - name: '1. Checkout github actions'
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
      env:
        ASPNETCORE_ENVIRONMENT: Production
    - name: Build
      run: docker build .
#      
#    - name: Build the docker-compose
#      run: docker-compose up -d
#    - name: Check running containers
#      run: docker ps -a
#    - name: Check logs
#      run: docker logs backend
#    - name: Run test suite
#      run: docker exec backend pytest --skip-auth
