name: Actions with docker
on:
  push:

jobs:  
  action_build:
    name: actions_build
    runs-on: ubuntu-latest
    
    steps:
    - name: 1. Checkout github actions
      uses: actions/checkout@v2
      
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs backend
    - name: Run test suite
      run: docker exec backend pytest --skip-auth
