name: CI github actions
on:
  push:

jobs:  
  build-and-test:
    name: Start of build
    runs-on: windows-latest #ubuntu-latest #windows-latest
    
    steps:
    - name: step#1 Checkout
      uses: actions/checkout@v2
    
    - name: step#2 Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100' #'2.2.108' #'3.1.100'
    - name: step#3 Build with dotnet
      run: dotnet build ./Swapify.sln #--configuration Release
      
    - name: step#4 Run tests
      run: dotnet test ./Tests/BackendTest/BackendTest.csproj #dotnet test --verbosity normal
    
    - name: step#5 Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12.11.1
    - name: step#6 npm install
      run: |
        cd WebApp
        npm install

    - name: step#7 npm test
      run: |
        cd WebApp
        npm test
        
    - name: step#8 gui tests
      run: |
        cd WebApp/testsGUI
        codeceptjs run
        
